# Global vars
vars:
  application: go-example-app
  version: 0.1

# Hosts
hosts:
  - host: localhost
    sudo: true
    user: vagrant
    password: vagrant
    port: 2222
    roles:
      - docker
      - db
    tasks:
      - task: echo
        description: echo Foo
        shell:
          command: echo "Foo"

# Role specific tasks
roles:
  common:
    tasks:
      - task: Common task
        shell:
          command: whoami
  docker:
    with: [common]
    tasks:
      - task: install docker
        description: Install docker
        apt-get:
          update: yes
          packages: [docker.io]
  db:
    with: [common]
    tasks:
      - task: Install MySQL
        apt-get:
          update: yes
          packages: [mysql-server]

# Global tasks
tasks:
  - task: env
    description: Get environment information
    shell:
      command: env
  - task: go
    description: Get go version
    shell:
      command: go version
