# Global vars
vars:
  application: go-example-app
  version: 0.1

# Hosts
hosts:
  - host: localhost
    description: "Foo"
    user: vagrant
    private_key: .vagrant/machines/default/virtualbox/private_key
    port: 2222
    roles:
      - docker
      - db
    tasks:
      - task: echo
        description: echo Foo
        shell:
          command: echo "Foo"

# Role specific tasks
roles:
  common:
    description: "Common"
    tasks:
      - task: Common task
        shell:
          command: whoami
  docker:
    description: "Docker base role"
    with: [common]
    tasks:
      - task: install docker
        description: Install docker
        apt:
          update: yes
          packages:
            - docker.io
  db:
    description: "DB role"
    with: [common]
    tasks:
      - task: Install MySQL
        apt:
          update: yes
          packages:
            - mysql-server

# Global tasks
tasks:
  - task: env
    description: Get environment information
    shell:
      command: env
  - task: go
    description: Get go version
    shell:
      command: go version
