# Global vars
vars:
  application: go-example-app
  version: 0.1

# Hosts
hosts:
  - host: localhost
    description: "Foo"
    user: vagrant
    private_key: .vagrant/machines/default/virtualbox/private_key
    port: 2222
    roles:
      - db
    tasks:
      - task: test
        description: Creates a temporary file
        shell:
          command: rm /tmp/kiss.ftw

# Role specific tasks
roles:
  common:
    description: "Common"
    tasks:
      - task: Common task
        shell:
          command: whoami
  db:
    description: "DB role"
    with: [common]
    tasks:
      - task: Install MySQL
        apt:
          update: true
          sudo: true
          packages:
            - mysql-server

# Global tasks
tasks:
  - task: env
    description: Get environment information
    shell:
      command: env
  - task: go
    description: Get go version
    shell:
      command: go version
