#! /usr/bin/env bash

echo "Test configuration"
pushd "configuration" >> /dev/null
  go get
  go test
popd >> /dev/null

echo "Test logging"
pushd "logging" >> /dev/null
  go get
  go test
popd >> /dev/null

echo "Test CLI"
pushd "kiss" >> /dev/null
  go get
  go test
popd >> /dev/null

echo "Test plugins"
pushd "plugins" >> /dev/null
  for D in `find . -mindepth 1 -maxdepth 1 -type d | grep -v core | grep -v shared`
  do
    pushd $D >> /dev/null
      go get
      go test
    popd >> /dev/null
  done
popd >> /dev/null
