---
tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  deploy:
    steps:
      - plugin: "env"
      - command: "echo"
        args:
        - "deploying..."
      - command: "echo"
        args:
        - "deployed!"
      - plugin: "ping"
