---
servergroups:
  localhost:
  web:
    - host: 10.10.0.0
      username: "root"
      password: "password"
      vars:
        mailgun_user: "user2valuehere"
        mailgun_key: "key2valuehere"
    - host: 10.10.0.1
      username: "root"
      password: "password"
      key_path: "/var/ssh/keys/"
  database:
    - host: 10.10.0.2
      username: "root"
      password: "password"
      vars:
        mailgun_user: "user2valuehere"
        mailgun_key: "key2valuehere"
tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  mailhello:
    steps:
      - plugin: "mailgun"
        options:
          user: api:key-1b065977e9b7901aeb70334e5f1d87aa
          endpoint: https://api.mailgun.net/v2/sandboxc68891711ef741188b13243239163728.mailgun.org/messages
          from: Mailgun Sandbox <postmaster@sandboxc68891711ef741188b13243239163728.mailgun.org>
          to: James <james+mailgun@creativenucleus.com>,
          subject: Hello James,
          text: Congratulations James, you just sent an email with Mailgun!  You are truly awesome!,
  deploy:
    steps:
      - command: "echo"
        args:
        - "deploying..."
      - plugin: "env"
      - command: "echo"
        args:
        - "- mid deploy -"
      - command: "echo"
        args:
        - "deployed!"
      - plugin: "ping"
        options:
          count: 3
          url: www.golang.org
  raiseerror:
    steps:
      - command: "echo"
        args:
        - "raise error"
      - command: "test"
        args:
        - "this should break"
triggers:
  testwebhook:
    type: webhook
    endpoint: prod
    servergroup: localhost
    task: sayhello
  gitpush:
    type: github-webhook
    endpoint: gitpush
    secret: mygithubsecrethere
    servergroup: localhost
    task: sayhello
  monitor:
    type: periodic
    period: 600
    servergroup: localhost
    task: sayhello
interfaces:
  web:
    settings:
      folder: /gokiss
      port: 20000
      sessionsecret: eIvObvXEiCzUZ61doiOX
    users:
      - username: james
        password: letmein
      - username: tobias
        password: sesame