---
tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  deploy:
    steps:
      - command: "echo"
        args:
        - "deploying..."
      - command: "echo"
        args:
        - "deployed!"
  raiseerror:
    steps:
      - command: "echo"
        args:
        - "raise error"
      - command: "test"
        args:
        - "this should break"
