---
tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  deploy:
    steps:
      - command: "echo"
        args:
        - "deploying..."
      - plugin: "env"
      - command: "echo"
        args:
        - "- mid deploy -"
      - command: "echo"
        args:
        - "deployed!"
      - plugin: "ping"
        args:
          - "-c 3"
          - "http://www.golang.org"
  raiseerror:
    steps:
      - command: "echo"
        args:
        - "raise error"
      - command: "test"
        args:
        - "this should break"