---
tasks:
  sayhello:
    steps:
      - command: "echo"
        args:
        - "hello"
  deploy:
    steps:
      - command: /usr/bin/whoami
        args:
      - plugin: "env"
      - command: "echo"
        args:
        - "deploying..."
      - command: "echo"
        args:
        - "deployed!"
      - plugin: "ping"
        args:
          - "-c 3"
          - "www.golang.org"
