tasks:
  setup:
    steps:
      - plugin: apt-get
        options:
          update: true
          packages:
            - "git"
      - plugin: git-clone
        options:
          repo: "https://github.com/Tobscher/go-three.git"
          directory: "go-three"
  deploy:
    steps:
      - plugin: whoami
      - plugin: env
      - plugin: ping
        options:
          count: 3
          url: www.golang.org
